import { useState } from 'react';
import { Cloud, ExternalLink, FolderPlus, KeyRound, LogOut, ShieldCheck, Trash2 } from 'lucide-react';
import { api } from '../api/client';
import { supportedTimeZones } from '../domain/timezone';

export type Preferences = { transcription: 'local' | 'openai' | 'gemini'; transcriptionFallback: 'openai' | 'gemini'; cleanup: 'none' | 'openai' | 'gemini'; language: string; timezone: string };

type Props = { preferences: Preferences; onPreferences(value: Preferences): void; folderId?: string | null; onChooseFolder(): void; onCreateFolder(): void; onSignedOut(): void };

export function Settings({ preferences, onPreferences, folderId, onChooseFolder, onCreateFolder, onSignedOut }: Props) {
  const [openai, setOpenai] = useState(''); const [gemini, setGemini] = useState(''); const [notice, setNotice] = useState('');
  const saveKeys = async () => { await api.configureProviders({ ...(openai ? { openai } : {}), ...(gemini ? { gemini } : {}) }); setOpenai(''); setGemini(''); setNotice('Encrypted provider credentials saved in your Drive folder.'); };
  const clearBrowser = async () => { indexedDB.deleteDatabase('voluble'); if ('caches' in window) await Promise.all((await caches.keys()).map((name) => caches.delete(name))); };
  return <div className="settings"><div className="section-heading"><div><span className="eyebrow">Preferences & privacy</span><h1>Settings</h1></div></div>
    <section className="settings-card"><h2><Cloud /> Speech processing</h2><div className="form-row"><label>Transcription<select value={preferences.transcription} onChange={(event) => onPreferences({ ...preferences, transcription: event.target.value as Preferences['transcription'] })}><option value="local">On-device when supported</option><option value="openai">OpenAI cloud</option><option value="gemini">Gemini cloud</option></select></label>{preferences.transcription === 'local' && <label>Cloud fallback<select value={preferences.transcriptionFallback} onChange={(event) => onPreferences({ ...preferences, transcriptionFallback: event.target.value as Preferences['transcriptionFallback'] })}><option value="openai">OpenAI</option><option value="gemini">Gemini</option></select></label>}<label>Cleanup & categorization<select value={preferences.cleanup} onChange={(event) => onPreferences({ ...preferences, cleanup: event.target.value as Preferences['cleanup'] })}><option value="none">None</option><option value="openai">OpenAI</option><option value="gemini">Gemini</option></select></label><label>Language<select value={preferences.language} onChange={(event) => onPreferences({ ...preferences, language: event.target.value })}><option value="en-US">English (US)</option><option value="en-GB">English (UK)</option><option value="es-ES">Spanish</option><option value="fr-FR">French</option></select></label><label>Time zone<select value={preferences.timezone} onChange={(event) => onPreferences({ ...preferences, timezone: event.target.value })}>{supportedTimeZones().map((timezone) => <option key={timezone} value={timezone}>{timezone.replace(/_/g, ' ')}</option>)}</select></label></div>{preferences.transcription === 'local' && <p className="fine-print">If on-device recognition is unavailable or stops unexpectedly, recording automatically continues with the selected cloud provider.</p>}</section>
    <section className="settings-card"><h2><KeyRound /> Provider credentials</h2><p>Keys are envelope-encrypted with AES-256-GCM and Google Cloud KMS. Plaintext is decrypted for one provider call only and never cached.</p><div className="form-row"><label>OpenAI API key<input type="password" autoComplete="off" value={openai} onChange={(event) => setOpenai(event.target.value)} /></label><label>Gemini API key<input type="password" autoComplete="off" value={gemini} onChange={(event) => setGemini(event.target.value)} /></label></div><button className="primary" disabled={!openai && !gemini} onClick={() => void saveKeys()}>Encrypt and save</button>{notice && <div className="notice success">{notice}</div>}</section>
    <section className="settings-card"><h2><ShieldCheck /> Drive & account</h2><div className="account-actions"><button onClick={onChooseFolder}>{folderId ? 'Reselect Drive folder' : 'Choose Drive folder'}</button><button onClick={onCreateFolder}><FolderPlus size={16} /> Create new Drive folder</button>{folderId && <a className="button-link" target="_blank" rel="noreferrer" href={`https://drive.google.com/drive/folders/${folderId}`}>Open Drive folder <ExternalLink size={15} /></a>}<button onClick={() => void api.logout().then(clearBrowser).then(onSignedOut)}><LogOut size={16} /> Sign out</button><button onClick={() => confirm('Disconnect Drive? Your Drive files will remain untouched.') && void api.disconnect().then(clearBrowser).then(onSignedOut)}>Disconnect Drive</button><button className="danger" onClick={() => confirm('Delete your Voluble account? Your selected Drive folder and all its contents will remain owned by you.') && void api.deleteAccount().then(clearBrowser).then(onSignedOut)}><Trash2 size={16} /> Delete Voluble account</button></div><p className="fine-print">Deleting your account removes sessions, encrypted tokens, folder pointers, and backend account data. Delete the Drive folder manually if you no longer want those files.</p></section>
  </div>;
}
