import { useState } from 'react';
import { Cloud, ExternalLink, FolderPlus, KeyRound, LogOut, ShieldCheck, Trash2 } from 'lucide-react';
import { api } from '../api/client';
import { supportedTimeZones } from '../domain/timezone';

export type Preferences = { transcription: 'local' | 'openai' | 'gemini'; transcriptionFallback: 'openai' | 'gemini'; cleanup: 'none' | 'openai' | 'gemini'; language: string; timezone: string };

type Props = { preferences: Preferences; onPreferences(value: Preferences): void; folderId?: string | null; onChooseFolder(): void; onCreateFolder(): void; onSignedOut(): void; onNotice(message: string): void; onProviderConfigured?(): void };

export function Settings({ preferences, onPreferences, folderId, onChooseFolder, onCreateFolder, onSignedOut, onNotice, onProviderConfigured }: Props) {
  const [openai, setOpenai] = useState(''); const [gemini, setGemini] = useState(''); const [notice, setNotice] = useState('');
  const requireFolder = () => { if (folderId) return true; onNotice('Choose your Drive folder before adding a provider API key.'); return false; };
  const saveKeys = async () => { if (!requireFolder()) return; if (!openai && !gemini) { onNotice('Enter an OpenAI or Gemini API key first.'); return; } await api.configureProviders({ ...(openai ? { openai } : {}), ...(gemini ? { gemini } : {}) }); setOpenai(''); setGemini(''); setNotice('Encrypted provider credentials saved in your Drive folder.'); onProviderConfigured?.(); };
  const clearBrowser = async () => { indexedDB.deleteDatabase('voluble'); if ('caches' in window) await Promise.all((await caches.keys()).map((name) => caches.delete(name))); };
  return <div className="settings"><div className="section-heading"><div><span className="eyebrow">Preferences & privacy</span><h1>Settings</h1></div></div>
    {!folderId && <section className="settings-card onboarding-step"><span className="eyebrow">Onboarding · Step 1</span><h2><FolderPlus /> Choose your Drive folder</h2><p>Voluble needs a folder before it can store encrypted provider credentials or records.</p><div className="account-actions"><button className="primary" onClick={onChooseFolder}>Choose existing folder</button><button onClick={onCreateFolder}>Create new folder</button></div></section>}
    <section className="settings-card"><h2><Cloud /> Speech processing</h2><div className="form-row"><label>Transcription<select value={preferences.transcription} onChange={(event) => onPreferences({ ...preferences, transcription: event.target.value as Preferences['transcription'] })}><option value="local">On-device when supported</option><option value="openai">OpenAI cloud</option><option value="gemini">Gemini cloud</option></select></label>{preferences.transcription === 'local' && <label>Cloud fallback<select value={preferences.transcriptionFallback} onChange={(event) => onPreferences({ ...preferences, transcriptionFallback: event.target.value as Preferences['transcriptionFallback'] })}><option value="openai">OpenAI</option><option value="gemini">Gemini</option></select></label>}<label>Cleanup & categorization<select value={preferences.cleanup} onChange={(event) => onPreferences({ ...preferences, cleanup: event.target.value as Preferences['cleanup'] })}><option value="none">None</option><option value="openai">OpenAI</option><option value="gemini">Gemini</option></select></label><label>Language<select value={preferences.language} onChange={(event) => onPreferences({ ...preferences, language: event.target.value })}><option value="en-US">English (US)</option><option value="en-GB">English (UK)</option><option value="es-ES">Spanish</option><option value="fr-FR">French</option></select></label><label>Time zone<select value={preferences.timezone} onChange={(event) => onPreferences({ ...preferences, timezone: event.target.value })}>{supportedTimeZones().map((timezone) => <option key={timezone} value={timezone}>{timezone.replace(/_/g, ' ')}</option>)}</select></label></div>{preferences.transcription === 'local' && <p className="fine-print">If on-device recognition is unavailable or stops unexpectedly, recording automatically continues with the selected cloud provider.</p>}</section>
    <section className={`settings-card ${!folderId ? 'locked-card' : ''}`} onClick={() => { if (!folderId) requireFolder(); }}>{folderId && <span className="eyebrow">Onboarding · Step 2</span>}<h2><KeyRound /> Provider credentials</h2><p>{folderId ? 'You can create your first 10 notes without a key. After that, add your own key here to continue with unlimited processing. Keys are envelope-encrypted with AES-256-GCM and Google Cloud KMS, decrypted for one provider call only, and never cached.' : 'Choose a Drive folder first. Encrypted provider credentials are stored inside that folder.'}</p><div className="form-row"><label>OpenAI API key<input type="password" autoComplete="off" readOnly={!folderId} value={openai} onFocus={requireFolder} onChange={(event) => setOpenai(event.target.value)} /></label><label>Gemini API key<input type="password" autoComplete="off" readOnly={!folderId} value={gemini} onFocus={requireFolder} onChange={(event) => setGemini(event.target.value)} /></label></div><button className="primary" aria-disabled={!folderId || (!openai && !gemini)} onClick={() => void saveKeys()}>Encrypt and save</button>{notice && <div className="notice success">{notice}</div>}</section>
    <section className="settings-card"><h2><ShieldCheck /> Drive & account</h2><div className="account-actions"><button onClick={onChooseFolder}>{folderId ? 'Reselect Drive folder' : 'Choose Drive folder'}</button><button onClick={onCreateFolder}><FolderPlus size={16} /> Create new Drive folder</button>{folderId && <a className="button-link" target="_blank" rel="noreferrer" href={`https://drive.google.com/drive/folders/${folderId}`}>Open Drive folder <ExternalLink size={15} /></a>}<button onClick={() => void api.logout().then(clearBrowser).then(onSignedOut)}><LogOut size={16} /> Sign out</button><button onClick={() => confirm('Disconnect Drive? Your Drive files will remain untouched.') && void api.disconnect().then(clearBrowser).then(onSignedOut)}>Disconnect Drive</button><button className="danger" onClick={() => confirm('Delete your Voluble account? Your selected Drive folder and all its contents will remain owned by you. A pseudonymous free-trial claim is retained to prevent repeated trial signup.') && void api.deleteAccount().then(clearBrowser).then(onSignedOut)}><Trash2 size={16} /> Delete Voluble account</button></div><p className="fine-print">Deleting your account removes sessions, encrypted tokens, folder pointers, and identifiable backend account data. A pseudonymous free-trial claim and usage count are retained for abuse prevention. Delete the Drive folder manually if you no longer want those files.</p></section>
  </div>;
}
